Интерфейс для плейлиста без реализаций.
Chebureck-Corporation/PlayLIST pull request #1
Opened 2020-10-31 22:38 UTC by phiest34

Сори за название ветки. Сделал минимальный функционал, пишите если что-то не так

2020-10-31 23:29 UTC, washinson commented
Сверху всякие кодстайл проверки, думаю их стоит починить

2020-10-31 23:51 UTC, washinson requested changes
Нужно доработать

2020-10-31 23:51 UTC, washinson commented on app/src/main/java/classes/PlaylistClass.kt
> +        fun or(playlists: ArrayList<PlaylistClass>) {}
Эти функции должны что-то возвращать, как я понимаю

2020-10-31 23:51 UTC, washinson commented on app/src/main/java/classes/PlaylistClass.kt
> +class PlaylistClass(
Может ограничимся пока интерфейсами?

2020-10-31 23:51 UTC, washinson commented on app/src/main/java/interfaces/Playlist.kt
> +//БД
Чтобы каши такой не было лучше юзать /* */

2020-10-31 23:51 UTC, washinson commented on app/src/main/java/interfaces/Playlist.kt
> +interface Playlist {
Маловато методов у PlayList
Я бы добавил ещё `getTracks()`, `delete(track: Track)` скорее всего должен принимать трек. За удаление плейлиста плейлист не отвечает:)

2020-10-31 23:51 UTC, washinson commented on app/src/main/java/classes/PlaylistClass.kt
> +class PlaylistClass(
Да, лучше убрать пока что этот класс и доделать интерфейс Playlist

2020-10-31 23:51 UTC, washinson commented on app/src/main/java/classes/Track.kt
> +data class Track(private val name: String, private val author: String, private val id: Int)
Думаю у `name` и `author` должны быть публичными

2020-10-31 23:51 UTC, washinson commented on app/src/main/java/interfaces/Playlist.kt
> +//поля: ID трека, ID плейлиста
Кажется здесь связь один ко многим у плейлиста и треков. Думаю стоит у трека хранить id плейлиста, а у плейлиста просто хранить его название и id

2020-10-31 23:51 UTC, washinson commented on app/src/main/java/interfaces/Playlist.kt
> +//название трека, автор,  ID
название, автор, id: int, playlist_id: int

2020-10-31 23:51 UTC, washinson commented on app/src/main/java/interfaces/Playlist.kt
> +//название плейлиста; ID
Зачем нам эта таблица и таблица `плейлисты`?

2020-11-01 12:14 UTC, phiest34 commented on app/src/main/java/interfaces/Playlist.kt
> +interface Playlist {
гетеры же сами генерируются...

2020-11-01 12:20 UTC, phiest34 commented on app/src/main/java/interfaces/Playlist.kt
> +//название трека, автор,  ID
зачем нам привязывать трек к конкретному плейлисту если он может находиться в разных, мы поэтому сделали просто список треков, и раскидали их и сказали какой к какому относиться, чтобы потом мы могли собрать плейлист зная его id и из таблицы по этому id вытягивать все треки которые в нем есть

2020-11-01 12:21 UTC, phiest34 commented on app/src/main/java/classes/Track.kt
> +data class Track(private val name: String, private val author: String, private val id: Int)
ну мы же все равно их сможем получать через гетеры, разве нет? зачем нам публичные поля

2020-11-01 14:05 UTC, washinson commented on app/src/main/java/interfaces/Playlist.kt
> +interface Playlist {
> гетеры же сами генерируются...
так чтобы они генерировались, нужно, чтобы свойства были где-то прописаны. В данном случае нужно прописать их в `Playlist`

2020-11-01 14:06 UTC, washinson commented on app/src/main/java/classes/Track.kt
> +data class Track(private val name: String, private val author: String, private val id: Int)
> ну мы же все равно их сможем получать через гетеры, разве нет?

Не сможем, можешь проверить)

2020-11-02 11:10 UTC, washinson requested changes

2020-11-02 11:10 UTC, washinson commented on app/src/main/java/interfaces/Playlist.kt
> +таблица: плейлисты
это не совсем таблица плейлисты, лучше её переименовать

2020-11-02 11:10 UTC, washinson commented on app/src/main/java/interfaces/Playlist.kt
> +    var tracks: ArrayList<Track>
Давай здесь пока что просто `List<Track>`

2020-11-02 11:25 UTC, washinson approved these changes
Все, ок, спасибо!

2020-11-02 11:25 UTC, merged