db-integration
Chebureck-Corporation/PlayLIST pull request #7
Opened 2020-11-06 13:19 UTC by phiest34

2020-11-06 18:54 UTC, washinson reviewed
Далее ещё посмотрю

2020-11-06 18:54 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/Entities.kt
> +@Entity(tableName = PLAYLISTS_TRACKS_ENTITY)
Тут надо `@Relation` добавить

2020-11-06 18:54 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/PlaylistDao.kt
> +    suspend fun getTracksOfPlaylist(playlistId: Int): List<Tracks>
Мы же решили юзать `LiveData`

2020-11-06 18:54 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/Entities.kt
> +data class Playlists(
Давай все-таки классы сделаем в единственном числе, а таблицы пусть будут во множественном
Я начал Dao смотреть и там боль :)

2020-11-06 18:54 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/Entities.kt
> +data class PlaylistsAndTracks(
Тут бы ещё кстати сделать ключи из `playlistId` и `trackId`

2020-11-06 18:54 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/PlaylistDao.kt
> +    suspend fun setPlaylistName(newName: String)
Здесь если мы хотим обновить `playlist` нам же нужен `id` плейлиста
И запрос тогда будет иметь вид: `UPDATE $PLAYLISTS_ENTITY SET name = :newName WHERE id = :id`

2020-11-09 00:15 UTC, washinson requested changes

2020-11-09 00:15 UTC, washinson commented on app/build.gradle
> +    kapt "android.arch.persistence.room:compiler:1.1.1"
Это уже не нужно, давай удалим

2020-11-09 00:15 UTC, washinson commented on app/src/androidTest/java/com/chebureck/playlist/ExampleInstrumentedTest.kt
> +import org.junit.Assert.assertEquals
Это зачем?

2020-11-09 00:15 UTC, washinson commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-6.5-all.zip
Это зачем?

2020-11-09 00:15 UTC, washinson commented on app/src/test/java/com/chebureck/playlist/ExampleUnitTest.kt
> +import org.junit.Assert.assertEquals
Тоже не уверен для чего это

2020-11-09 00:15 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/Entities.kt
> +data class PlaylistEntity(
Давай переименуем `PlaylistEntity` в `Playlist`
Ранее созданные интерфейсы `Playlist` пока трогать не будем

2020-11-09 00:15 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/Entities.kt
> +    val name: String?
`name` не Nullable

2020-11-09 00:15 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/Entities.kt
> +data class TrackEntity(
Давай уберем `Entity` везде

2020-11-09 00:15 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/Entities.kt
> +    val author: String?
Тоже все не Nullable

2020-11-09 00:15 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/Entities.kt
> +    @ColumnInfo(name = PLAYLIST_ID_FIELD) val playlistId: Long,
`Relation` надо сюда

2020-11-09 00:15 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/Entities.kt
> +data class PlaylistWithTracks(
Это не нужно скорее всего

2020-11-09 00:15 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/PlaylistDao.kt
> +    fun getPlaylistsWithTracks(): LiveData<List<PlaylistWithTracks>>
У этого есть прикладное применение? Может удалим?

2020-11-09 00:15 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/PlaylistDao.kt
> +    suspend fun getPlaylistById(playlistId: Long): PlaylistEntity
`suspend` точно нужен? 
Не видел кода, где используется

2020-11-09 00:15 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/PlaylistDao.kt
> +    suspend fun getTrackNameById(trackId: Long): String
Давай пока не будем много специфичного кода писать. Если нужно будет имя, достанем плейлист и из него имя достанем

2020-11-09 00:15 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/PlaylistDao.kt
> +    suspend fun getPlaylistNameById(playlistId: Long): String
Специфичный код

2020-11-09 00:15 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/PlaylistDao.kt
> +    suspend fun setPlaylistName(newName: String, playlistId: Long)
Специфичная функция

2020-11-09 00:15 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/PlaylistDao.kt
> +    @Transaction
Мы тут делаем одно действие, зачем `Transaction`?

2020-11-09 00:15 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/PlaylistDao.kt
> +    @Transaction
Лишняя `Transaction`

2020-11-09 00:15 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/PlaylistDao.kt
> +    suspend fun removeTrack(trackId: Long)
Специфичный код

2020-11-09 00:15 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/PlaylistDao.kt
> +    suspend fun removePlaylist(playlistId: Long)
Специфичный код

2020-11-09 00:15 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/PlaylistDatabase.kt
> +    companion object {
Давай это удалим. Все таки за создание `Database` будет отвечать кто-то другой. Потом напишем.

2020-11-09 07:43 UTC, phiest34 commented on app/src/androidTest/java/com/chebureck/playlist/ExampleInstrumentedTest.kt
> +import org.junit.Assert.assertEquals
ктлинт не любит , когда звездочки используются

2020-11-09 07:49 UTC, phiest34 commented on app/src/main/java/com/chebureck/playlist/db/PlaylistDao.kt
> +    suspend fun setPlaylistName(newName: String, playlistId: Long)
да вроде нет, у нас должна быть возможность кастомные плейлисты уметь переименовывать

2020-11-09 08:09 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/PlaylistDao.kt
> +    suspend fun setPlaylistName(newName: String, playlistId: Long)
Да, для этого есть `@Update`

2020-11-09 08:10 UTC, washinson commented on app/src/androidTest/java/com/chebureck/playlist/ExampleInstrumentedTest.kt
> +import org.junit.Assert.assertEquals
Блин блинский. Какой-то он стремный этот ktlint )

2020-11-10 16:00 UTC, washinson requested changes

2020-11-10 16:00 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/Playlists.kt
> +package com.chebureck.playlist.db
Это интерфейс плейлиста, а не плейлистов. Давай обратно переименуем

2020-11-10 16:00 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/Tracks.kt
Это интерфейс трека. Давай обратно переименуем

2020-11-10 16:00 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/PlaylistDao.kt
> +    @Transaction
Лишние `@Transaction`

2020-11-10 16:00 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/PlaylistDao.kt
> +    @Transaction
Лишние `@Transaction`

2020-11-10 16:00 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/db/Playlists.kt
> +package com.chebureck.playlist.db
Идея именно в том, чтобы это мы уже юзали на стороне приложения. Так можно быть независимым от логики БД. Далее напишем `wrapper`'ы на эти интерфейсы

2020-11-10 21:44 UTC, washinson approved these changes
Вроде все ок, заливаем

2020-11-10 21:44 UTC, merged