Верстка одного экрана и одного диалогового фрагмента (без стилей)
Chebureck-Corporation/PlayLIST pull request #8
Opened 2020-11-11 21:48 UTC by phiest34

2020-11-12 14:59 UTC, CustomNick commented
Вроде все норм, у меня нет замечаний

2020-11-12 16:44 UTC, CustomNick approved these changes
Все норм

2020-11-12 19:56 UTC, washinson requested changes
Почти все ок, давай комменты починим и заливаем

2020-11-12 19:56 UTC, washinson commented on app/src/main/res/layout/fragment_authentication.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Советовали не юзать просто так `ConstraintLayout`. Давай заменим на `RelativeLayout`

2020-11-12 19:56 UTC, washinson commented on app/src/main/res/layout/dialog_edit_list.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Советовали не юзать просто так `ConstraintLayout`. Давай заменим на `RelativeLayout`

2020-11-12 19:56 UTC, washinson commented on app/src/main/res/values/strings.xml
> +    <string name="string_login">Войдите в аккуант</string>
Тут бы англичанские буквы, а в `values-ru` русские

2020-11-12 19:56 UTC, washinson commented on app/src/main/res/layout/dialog_edit_list.xml
> +<androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
Мне кажется, что эта xml вообще из другой оперы. Давай её в соотв PR зальем. Тут удалим

2020-11-16 12:33 UTC, washinson approved these changes

2020-11-16 12:33 UTC, merged