Верстка экранов с треками (скорее всего надо будет что-нибудь поменять)
Chebureck-Corporation/PlayLIST pull request #9
Opened 2020-11-11 21:53 UTC by CustomNick

2020-11-12 11:40 UTC, phiest34 commented on app/src/main/res/layout/fragment_tracks_screen.xml
> +                android:layout_height="wrap_content"/>
нет id у view

2020-11-12 11:40 UTC, phiest34 commented on app/src/main/res/layout/fragment_tracks_screen.xml
> +        <androidx.appcompat.widget.AppCompatButton
так же нет id

2020-11-12 11:41 UTC, phiest34 commented on app/src/main/res/layout/fragment_tracks_screen.xml
> +        <TextView
cюда бы тоже id

2020-11-12 11:43 UTC, phiest34 commented on app/src/main/res/drawable/circle_button.xml
> +            android:color="#000000"/>
цвет можно вынести в values

2020-11-12 14:09 UTC, phiest34 reviewed
Больше проблем пока не увидел

2020-11-12 19:01 UTC, phiest34 approved these changes
Все устраивает

2020-11-12 19:41 UTC, washinson requested changes
Почти ок, но можно ещё написать адаптеры и `ViewHolder'ы`. Давай сделаем и комменты пофиксим?

2020-11-12 19:41 UTC, washinson commented on app/src/main/res/drawable/circle_button.xml
> +<shape
Давай все таки придерживаться кодстайлу. 
В студии `Ctrl+Alt+L` обновит код.
У меня получилось вот так 
```
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
        android:shape="oval">

    <solid android:color="@color/black" />

    <size
            android:width="10dp"
            android:height="10dp" />
</shape>
```

2020-11-12 19:41 UTC, washinson commented on app/src/main/res/drawable/name_border.xml
> +<?xml version="1.0" encoding="utf-8"?>
Этот xml не используется
Зачем он нужен?

2020-11-12 19:41 UTC, washinson commented on app/src/main/res/layout/fragment_tracks_screen.xml
> +<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
Давай лучше `RelativeLayout`, чтобы избежать вложенности

2020-11-12 19:41 UTC, washinson commented on app/src/main/res/layout/fragment_tracks_screen.xml
> +    <LinearLayout
Вот этой вложенности

2020-11-12 19:41 UTC, washinson commented on app/src/main/res/values/button_style.xml
> +<?xml version="1.0" encoding="utf-8"?>
Стиль не используется. Давай удалим

2020-11-12 19:41 UTC, washinson commented on app/src/main/res/layout/fragment_tracks_screen.xml
> +                android:gravity="center_horizontal"
Давай лучше просто `center` так красивше выглядит)

2020-11-26 00:01 UTC, washinson approved these changes

2020-11-26 00:01 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/viewholders/TrackViewHolder.kt
> +        authorName = this.itemView.findViewById(R.id.text_author)
Тут можно сразу иницилизировать поля

2020-11-26 00:09 UTC, washinson requested changes

2020-11-26 00:09 UTC, washinson commented on app/src/main/java/com/chebureck/playlist/adapters/TrackAdapter.kt
> +        val layout: View = inflater.inflate(R.layout.track, parent, false)
не верстки `track`, залей плз

2020-11-26 08:11 UTC, washinson approved these changes

2020-11-26 08:11 UTC, merged